name: Trash
version: '1.0'
main: me.fini69.trash.Trash
api-version: '1.21.1'
authors: [ fini69 ]
description: Get rid of the items in your inventory using Trash Bin.

commands:
  trash:
    description: Opens a menu where you can discard any unwanted items.
    usage: /<command>
    permission: trash.use
    aliases: [ bin, trashbin, garbage, kosz, mull ]
  trashreload:
    description: Reloads the plugin configuration.
    usage: /trashreload
    permission: trash.reload

permissions:
    trash.use:
        description: Access to the Trash Command.
        default: true
    trash.reload:
      description: Allows reloading the plugin configuration.
      default: op